language: objective-c
osx_image: xcode7.2
before_install:
  - gem install xcpretty -N
script:
  - set -o pipefail
  - xcodebuild -project AudioTuning/AudioTuning.xcodeproj -scheme "AudioTuning" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=latest" ONLY_ACTIVE_ARCH=NO test | xcpretty -c
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
